### ISSUE TITLE
Pixel positions for Astri are wrong in h5 files 

### ISSUE THREAD

**Issue by qi-feng** [cta-observatory/dl1-data-handler#23]
The pixel positions in the h5 file for SSTA are that from low to high pixel number, the camera is filled row by row from bottom left to the top right. However, it seems that the ASTRI camera should be filed from top left to bottom right by 8x8 sub-module sectors.

**Comment by bryankim96** [comment]
I will try to look into the current version of ctapipe and see if this has been corrected and if not, maybe we should post an issue there, as this isn't something we can directly control. The pixel positions are written here:

https://github.com/cta-observatory/image-extractor/blob/efe92aedc2ea422c4e3e1985061f7666c9f529e5/image-extractor/image_extractor.py#L275-L279

They're extracted straight from the event's instrument container without any modification (besides padding). We can manually try to correct it within image-extractor but this seems like it isn't the right way to handle it.

**Comment by TjarkMiener** [comment]
I'm currently reading the pixel positions from the fits file from [https://github.com/cta-observatory/ctapipe-extra](url), which are identical to the ones in the h5 files. The camera is filled row by row from bottom left to the top right:
![astricam_oversamplingtest](https://user-images.githubusercontent.com/37835610/51481418-1e2ad680-1d94-11e9-8e3d-ddeb689b2574.png)

Why it seems that the ASTRI camera should be filled from top left to bottom right by 8x8 sub-module sectors? I searched for a gamma shower that triggered ASTRI, CHEC and DigiCam at the same location. So I plotted the same event at the same location with different SST's and the shower orientation is the same. Due to the larger FoV of ASTRI, the shower of ASTRI is closer to the center of the camera than CHEC and DigiCam.  

![ssta_1_bicubic](https://user-images.githubusercontent.com/37835610/51481938-6c8ca500-1d95-11e9-8379-8178dc28fc71.png)
![sst1_1_bicubic](https://user-images.githubusercontent.com/37835610/51481943-6eeeff00-1d95-11e9-8cbc-dbd63dc2a83f.png)
![sstc_1_bicubic](https://user-images.githubusercontent.com/37835610/51481947-71e9ef80-1d95-11e9-9730-66d50ef2facb.png)

**Comment by bryankim96** [comment]
As far as I can tell this will not require any specific action for the foreseeable future, so I'll close it. We can reopen a similar issue when the question of using real data becomes more defined.
