### ISSUE TITLE
Simplify requirements file

### ISSUE THREAD

**Issue by aribrill** [cta-observatory/dl1-data-handler#32]
The requirements for DL1DataHandler are currently listed in two separate files, requirements.txt and environment.yml. Is there a reason for this or is it possible to provide just environment.yml? Also, the environment file should only specify the top-level dependencies (currently setuptools, numpy, pytables, amd pyyaml). Lower-level dependencies will be automatically installed and don't need to be specified.

**Comment by bryankim96** [comment]
It's because if you want to install all packages from a file with pip, you need a file formatted like requirements.txt, while doing the same with conda requires that specific YAML format. The two files were automatically generated using pip and conda respectively. It's purely for convenience/supporting both installation methods. The pip one can be simplified using a utility like pipreqs (https://pypi.org/project/pipreqs/), the reason it shows all dependencies explicitly is because that's how the output generated by the native pip freeze looks. 

Ultimately it might make more sense to remove the pip requirements file and instead have the dependencies list in setup.py.

**Comment by bryankim96** [comment]
The installation method was simplified to use only pip/setuptools in https://github.com/cta-observatory/dl1-data-handler/commit/1a7f6851f897726793221a380547065af498434c. Going forwards we can try to register the package on conda or PyPI.
