### ISSUE TITLE
repository size

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/dl1-data-handler#39]
Hi
I am just wondering why is the repo already ~30MB large?

**Comment by bryankim96** [comment]
You're right. Nearly all of the ~30 MB is due to the .git folder. This is because at some point in the past there were large files in the repository. Although they've been removed now, they were maintained as objects in the git history. This caused the .git folder to remain large. I've since cleaned up/rewritten the history to exclude the past large files w/ a forced update and the size has been reduced to < 1 MB. In order to prevent the history from being overwritten to include the large objects again, it is vital that you make a fresh clone of the repository before pushing any new changes.
