### ISSUE TITLE
Reduce size of conda package

### ISSUE THREAD

**Issue by aribrill** [cta-observatory/dl1-data-handler#53]
As can be seen [here](https://anaconda.org/bryankim96/dl1_data_handler/files), the conda package for DL1DH 0.7.4 is 248 MB. The package for v0.7.2 was only 126.2 kB. Perhaps this is related to #39?

**Comment by bryankim96** [comment]
That's a pretty ridiculous increase... Let me take a look at this again. From what I can see it's definitely not due to the same issue in #39, as even at its largest the .git folder was only ~30 MB. I have some some somewhat large test data files and notebooks in my repository, but these aren't being tracked in master and they're not within the python module part of the repo either... Maybe they somehow got included into the tarball inadvertently? Let me take a look

**Comment by bryankim96** [comment]
This appears to have been the issue (including other extraneous files in the directory when building the conda package tarball). We should keep this in mind in the future when uploading releases.

**Comment by kosack** [comment]
You should probably build directly from the git repo, rather than a local directory
