### ISSUE TITLE
Update to ctapipe v0.7.0 

### ISSUE THREAD

**Issue by TjarkMiener** [cta-observatory/dl1-data-handler#74]
I tried to update to `ctapipe v0.7.0` (or/and current master of ctapipe). So far, I'm able to produce the h5 files without any breaks. However, my configurations of the `ctapipe CameraCalibrater` or of the `ctapipe GainSelector` are not right. Can anyone (more familiar with ctapipe) please have a look into this? You can find the code [here](https://github.com/cta-observatory/dl1-data-handler/tree/update_ctapipe). Thanks in advance! The 'charge' channel seems to be working fine, while the 'pulse_time' channel is messed up.
![LSTCam_gamma_66_charge](https://user-images.githubusercontent.com/37835610/66048971-d5363f00-e52a-11e9-9208-6ab7fb8341f2.png)
![LSTCam_gamma_66_time](https://user-images.githubusercontent.com/37835610/66048972-d5363f00-e52a-11e9-8252-fdd25b9f2e62.png)

**Comment by vuillaut** [comment]
Hi @TjarkMiener.
Thank you for looking into this. I was thinking about it but really didn't have time.
Not sure the pulse time map is messed-up without the scale. The way the time map is computed has changed and I think the color representation is misleading you here.

**Comment by TjarkMiener** [comment]
Thanks for the quick response, @vuillaut! It seems you are right. It's a matter of color representation. However, we are puzzled, why we are getting the time arrival values in this ranges?

I plotted the same event with a colorbar:
![LSTCam_gamma_66_time](https://user-images.githubusercontent.com/37835610/66057691-71ffd900-e539-11e9-8932-8e307c15c016.png)

I plotted a histogram of the time arrival of the same event:
![LSTCam_histogram_gamma_66_time](https://user-images.githubusercontent.com/37835610/66057576-411fa400-e539-11e9-86bc-205d9cd08429.png)

I plotted the same event (in logscale) with a colorbar:
(Here one can spot the shower)
![LSTCam_logscale_gamma_66_time](https://user-images.githubusercontent.com/37835610/66057726-8512a900-e539-11e9-8df7-ec0d925dcb0d.png)

**Comment by kosack** [comment]
If you think the values are not correct, can you post an issue on the ctapipe issue tracker? Not so many devs read this one.  

By the way, you can just set `display.norm = 'log'` to show a log-scale image, rather than modifying the values.

**Comment by vuillaut** [comment]
I don't think the values are incorrect but follow a very different scale which is not `ns` anymore.
However, I see in the ctapipe function `extract_pulse_time_around_peak` that there is a `# TODO: Return pulse time in units of ns instead of isample`. So maybe still post an issue to remind everybody that's something to improve :)

**Comment by kosack** [comment]
They should be nanoseconds. If not, I would suggest submitting an issue. 

That TODO i believe was due to the fact that in basically all of the calibration and trace integration code, we never multiplied by the clock frequency (so many distributions were wrong for FlashCam, which use 250MHz sampling).  For GHz samplers, it's still correct, since the correction factor to nanoseconds is 1.0.  So if LST data are not in ns, I'd call that a bug.

**Comment by TjarkMiener** [comment]
I redid this exercise with the current master (after the fix [ctapipe PR #1143](https://github.com/cta-observatory/ctapipe/pull/1143)) and it gives reasonable values for the pulse time channel:

![Para_LSTCam_logscale_gamma_66_time](https://user-images.githubusercontent.com/37835610/69330270-e9590b80-0c52-11ea-9a12-cf9118977e0c.png)
![Para_LSTCam_histogram_gamma_66_time](https://user-images.githubusercontent.com/37835610/69330347-08579d80-0c53-11ea-8886-60f2c3c509c6.png)
