### ISSUE TITLE
ImageMapper: nearest interpolation normalization

### ISSUE THREAD

**Issue by mikael10j** [cta-observatory/dl1-data-handler#86]
Hi,

I was wondering if the nearest neighbors interpolation method implemented in ImageMapper should normalize pixels to preserve overall intensity ?

I might do something wrong but I found out that it's not:

![image](https://user-images.githubusercontent.com/10218967/81093079-df298180-8f01-11ea-9441-56d575045471.png)

any clue ?

**Comment by MaxNoe** [comment]
Why is the LSTCam rotated like this? Depending on coordinate frame it should either have a flat top (hess/simtel coordinate frame == ctapipe.coordinate.CameraFrame) or it should have a pointy top (FACT/MAGIC frame == ctapipe.coordinates.EngineeringCameraFrame)

**Comment by mikael10j** [comment]
The purpose of the image mapper is either to resample original images or to provide their index matrix (for IndexedConv) in order to be able to process them with deep learning frameworks. As you can see on the figure below, in the case of hexagonal grid camera like LSTCam, rotating the frame  allows to have one axis of the axial addressing system (in red) aligned with the x axis of the Cartesian grid. This is required to produce the index matrix of the camera. This is also required if the "resampling" method is image_shifting.

![image](https://user-images.githubusercontent.com/10218967/81161999-c914d300-8f8c-11ea-8bbf-61adb8e69269.png)

**Comment by TjarkMiener** [comment]
The oversampling (and rebinning) method is preserving the pixel intensity by default. If I remember correctly, we excluded nearest neighbors interpolation on purpose, because the output pixels should have the value of the corresponding nearest neighbor. Therefore we decided to not normailze the mapping tables for this method. However, one can argue that this argument is also valid for the other interpolation methods, because the output pixels should be a weighted sum of their neighbors for bilinear interpolation. So I think we should normalize the mapping tables for all interpolation types.

Thanks for sharing the illustrative plots, @mikael10j!  One minor side note, the argument 'rotate_back' in the imagemapper (IM) is rotating the mapping tables to the original orientation. This is done with an extra interpolation (using `scipy.ndimage.rotate`) on top of the IM interpolation. If the original orientation have to be preserve, I would recommend to not use the IM with this argument and interpolate event-based with `scipy` directly. Now if I think of this argument, I noticed that when we switch to the GammaLearn image convention (flipping the y-axis), the rotation back is failing. Should we fix this or completely remove this (weak) features? We don't need this for our DL studies.

**Comment by mikael10j** [comment]
Thank you for your answer @TjarkMiener . I supposed that nearest neighbor should also be normalized because of a sentence in our ICRC paper about image resampling. I don't see any issue if it's not, for the neural network it's just a matter of scaling factor.

About the rotate_back argument, I also don't think we need it.
