### ISSUE TITLE
Switch to use ctapipe-stage1?

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/dl1-data-handler#92]
Hi,

As the ctapipe stage1 tool is now available and writes images and parameters in a standard way, 
would you consider using that instead of duplicating efforts?

Is there something missing from the stage1 tool you need?

Do you need some support that would enable you to make the switch?

**Comment by vuillaut** [comment]
Hi

Yes it has always been an explicit goal to switch to stage1 tool at some point, keeping here only  the reader for DL studies.

This requires to:
- test thoroughly the stage1 DL1 (anyone ?)
- modify the reader, which will require some work

**Comment by maxnoe** [comment]
Yes, also note that ctapipe 0.10 is imminent (today or tomorrow) with fixes also for the stage1 output. So it would be great if you could test it as soon as 0.10 is out.

**Comment by maxnoe** [comment]
For the reading part, ctapipe 0.10 also includes the `DL1EventSource`, which can be used to iterate event wise.

But for most applications, I think you don't actually want that and instead just use `ctapipe.io.astropy_helpers.h5_table_to_astropy` to read a whole table into an astropy table, e.g. all images of one telescope.

**Comment by kosack** [comment]
Note that that function is aliased to `ctapipe.io.read_table`. Soon I'll add a tutorial on working with the DL1 data files, including merging datasets, etc, which could be useful for you

**Comment by nietootein** [comment]
Thanks for opening this issue, @maxnoe !

As @vuillaut said, we'd like to switch to stage1 at some point. 

While waiting for that tool, @TjarkMiener and @sahilyadav27 have been expanding the writer so we can now dump MAGIC data in ROOT format to hdf5 (see #90), aiming at implementing similar functionality for VERITAS and H.E.S.S. data as well (with the purpose of using our DL frameworks on data from current gen IACTs). Is this feature something envisioned for stage1?

Additionally, @LucaRomanato and @TjarkMiener have recently implemented the calculation and addition of image parameters to the writer (see #91), not only for CTA cameras.

I wonder if some of these and other functionalities (e.g. imagemapper transformations) could be of interest for stage1 users other than us, so to transfer them there?

**Comment by maxnoe** [comment]
> Is this feature something envisioned for stage1?

Yes, you just need to implement an event source in a package called `ctapipe_io_<name>` and the stage1 tool will automatically choose a compatible event source if available.

I am currently developing this here for LST raw data in zfits format: https://github.com/cta-observatory/ctapipe_io_lst/pull/44

I can have a look at your event sources and what is needed to make them compatible so the stage1 (and any other tool using `EventSource` for input data, like plotting for example)  can be used.

**Comment by maxnoe** [comment]
Actually there is already https://github.com/cta-observatory/ctapipe_io_magic, which has not seen updates in a long time, but shouldn't be to hard to update it so it is compatible with the latest ctapipe.

**Comment by kosack** [comment]
> While waiting for that tool, @TjarkMiener and @sahilyadav27 have been expanding the writer so we can now dump MAGIC data in ROOT format to hdf5 (see #90), aiming at implementing similar functionality for VERITAS and H.E.S.S. data as well (with the purpose of using our DL frameworks on data from current gen IACTs). Is this feature something envisioned for stage1?

I really feel like there is a lot of duplicated work here... We have readers for MAGIC and HESS already in fact, though they probably need some updates for the latest version.  It would be good to coordinate with ctapipe more otherwise this is a lot of wasted effort!

**Comment by vuillaut** [comment]
> > Is this feature something envisioned for stage1?
> 
> Yes, you just need to implement an event source in a package called `ctapipe_io_<name>` and the stage1 tool will automatically choose a compatible event source if available.
> 
> I am currently developing this here for LST raw data in zfits format: [cta-observatory/ctapipe_io_lst#44](https://github.com/cta-observatory/ctapipe_io_lst/pull/44)
> 
> I can have a look at your event sources and what is needed to make them compatible so the stage1 (and any other tool using `EventSource` for input data, like plotting for example) can be used.
> 
> > Additionally, @LucaRomanato and @TjarkMiener have recently implemented the calculation and addition of image parameters to the writer (see #91), not only for CTA cameras.
> 
> ctapipe can calculate image features for all telescopes, the only thing needed is that the `EventSource` implementation provides the correct `SubarrayDescription`

I don't think event source is the priority for DL applications.

**Comment by TjarkMiener** [comment]
Thanks for this thread, @maxnoe 

As @vuillaut and @nietootein already mentioned, we do have plans to move to the stage1! We will do so when there is a production (Prod5?) available. I think I already volunteer for the second point on Thomas list to update the DL1 reader. Should be relatively easy since the data formats are quite similar. Due to some deadlines, we decided to implement the MAGIC stuff ourselves. ctapipe_io_magic is quite outdated on GitHub. There is also a gitlab repo but it isn't synchronised with the GitHub one. It wasn't really working for us at that time (we were in contact with the core developers), so we didn't wait. However, the MAGIC DL working group (where the effort started from) is only interested in DL studies, so they decided to adopt the dl1dh + ctlearn or custom DL code, which is tested and in place, for their studies. So I think it wasn't a wasted effort!

@kosack: Regarding the reading, what do you mean with joining and merging datasets? We will have a look, once it's public. Thanks! There was some recent improvement of the data reading performance by @aribrill. Please find it [here](https://github.com/cta-observatory/dl1-data-handler/pull/88) and [here](https://github.com/ctlearn-project/ctlearn/pull/131). This is our bottleneck for the DL studies, so we (mainly Ari) constantly improving the dl1 reader and make the reading more efficient for our use case. For the standard analysis the use case probably differs.

@nietootein: About moving the ImageMapper. I think this is something Karl already suggested a year ago. I spent some time to remove the ctapipe dependency in the IM, so that our DL analysis is independent from ctapipe-extra (I think the ctapipe did something similar for their analysis; just remembered reading a discussion from @maxnoe ). Moving individual classes, which are required for the dl1 reader, to ctapipe, would make the installation quite messy. However, if the IM still of interested for non DL people, we can discuss this.

**Comment by TjarkMiener** [comment]
Solved by v0.10.0
